### PR TITLE
added ui for summarization and backend code for it

### PR DESCRIPTION
**Pull request by Anash3**
Created UI for selecting OpenAI model, inputting API key, and summarization text, and displaying the result

### CODE REVIEW

**Comment by Anash3** [comment]
can i know what was the problem with the code 
i was able to run the project locally

**Comment by Elijas** [comment]
Hi @Anash3,

Thanks for your contributions and for taking the time to create the UI for summarization and its backend code! It's awesome to see first-time contributors diving right in.

To address your query about the code, running the following commands should highlight any issues:

```
pip install ruff
cd sec-parser
ruff check --fix sec_parser/
```

🚀 These commands will check for errors and attempt to fix them automatically. 

Looking forward to your response!

Best,
Elijas

**Comment by Anash3** [comment]
Thank you @Elijas for the help
i have ran the given commands and solved all the issue 
can you review the code and let me know the feedback

**Comment by Elijas** [comment]
Hi @Anash3,

First of all, thank you for your valuable contributions and the effort you've put into enhancing `sec-ai`, especially as a first-time contributor. Your code and approach look promising.

However, our team is currently laser-focused on a different but critical component of the project: `sec-parser`. As a result, we are deferring new features and enhancements outside of this scope for the time being.

Please note that deferring the PR doesn't mean it won't be useful in the future; it might become relevant once our current objectives are met. For guidelines on how you can contribute to the `sec-parser` project, feel free to visit our [Contribution Guidelines](https://github.com/alphanome-ai/sec-parser/blob/main/CONTRIBUTING.md).

We appreciate your understanding and look forward to potentially revisiting your contributions when the time is right.

Feel free to reach out if you have any questions or concerns. Thank you for your understanding, and we look forward to your continued interest in the project.

Thanks,
Elijas

**Comment by Elijas** [comment]
Hey, would you consider revisiting this solution to solve 
https://github.com/alphanome-ai/sec-ai/issues/39

**Comment by alphanome** [comment]
PR closed due to 1 month of inactivity. Please, consider reopening this PR with this Github Issue in mind: https://github.com/alphanome-ai/sec-ai/issues/39

**Pull request closed without merging**
